# Generated by Django 5.1.5 on 2025-01-25 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idClasse', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=20)),
                ('Filiere', models.CharField(max_length=20)),
                ('niveau', models.TextField(choices=[('1', 'Niveau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3'), ('4', 'Niveau 4'), ('5', 'Niveau 5')], default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('idMatiere', models.AutoField(primary_key=True, serialize=False)),
                ('Id_UE', models.CharField(max_length=50)),
                ('Coef', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('enseignant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idEtudiant', models.AutoField(primary_key=True, serialize=False)),
                ('Matricule', models.CharField(max_length=20)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Sexe', models.TextField(choices=[('F', 'Feminin'), ('M', 'Masculin')], default='')),
                ('image', models.ImageField(default='C:/Users/YONTA/Desktop/PROJET IUC/projetPy/projetPy/photo_profil_base.jpg', upload_to='')),
                ('classe', models.ForeignKey(default='iuc', on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='listing.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('idClasse', models.ForeignKey(default='iuc', on_delete=django.db.models.deletion.CASCADE, related_name='dispenser', to='listing.classe')),
                ('idMatiere', models.ForeignKey(default='cours', on_delete=django.db.models.deletion.CASCADE, to='listing.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Eval', models.TextField(choices=[('Eval_1', 'Evaluation 1'), ('Eval_2', 'Evaluation 2'), ('Eval_3', 'Evaluation 3')], default='0')),
                ('valeur', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('remarques', models.TextField(default="la reussite s'arrache", max_length=100)),
                ('dateEval', models.DateTimeField()),
                ('dateRemplissage', models.DateTimeField()),
                ('idClasse', models.ForeignKey(default='iuc', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='listing.classe')),
                ('idEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.etudiant')),
                ('idMatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.matiere')),
            ],
        ),
    ]
