# Generated by Django 5.1.5 on 2025-01-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_note_n_eval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='idClasse',
        ),
    ]
