# Generated by Django 5.1.5 on 2025-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_note_idclasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
