# Generated by Django 5.1.5 on 2025-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
