# Generated by Django 5.1.4 on 2025-01-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlisting',
            name='Matricule',
            field=models.CharField(default='iuc', max_length=30),
        ),
    ]
